language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t  kylvia/jkouBlog:latest .
  - docker tag kylvia/jkouBlog:latest jiaoa/jkouBlog:latest
  - docker push jiaoa/jkouBlog:latest
