language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - docker build -t jkou_blog .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push jkou_blog
