language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  - npm install

script:
  - umi build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t joynce_blog .
  - docker tag joynce_blog jiaoa/joynce_blog:latest
  - docker push jiaoa/joynce_blog
