language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  - npm install

script:
  - umi build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jkou_blog .
  - docker push jkou_blog
